/**
 * Living Micro-Interactions & Frontend Polish Skill
 * Ensures generated websites feel alive, tactile, and fully functional, not static mockup shells.
 */
export const INTERACTION_SKILL = `
=== LIVING MICRO-INTERACTIONS & JAVASCRIPT POLISH RULES ===

A website generated by WebGenie MUST NOT BE A DUMB STATIC SHELL. Every interactive element must actually work!

1. FULLY FUNCTIONAL MODALS:
- If a "Book Now", "Contact", "Get Started", or "Quick View" modal is present:
  * Clicking the trigger button must open the modal with a smooth fade & scale transition.
  * Clicking the backdrop, close button, or pressing the [Escape] key must close the modal.
  * Submitting the modal form must prevent default page reload, show a loading spinner on the button, and display a success state (e.g. "Appointment Confirmed for John! We sent a confirmation to your email.").

2. DYNAMIC TAB & CATEGORY FILTERING:
- For galleries, price lists, or feature showcases with filter tabs (e.g., "All", "Haircuts", "Beard", "Treatments"):
  * Implement instant JS category filtering (filtering DOM elements with smooth opacity transitions).
  * Visually highlight the active tab with high-contrast styling.

3. STICKY NAVBAR WITH SCROLL DETECTION:
- Header must smoothly transition background opacity and border on window scroll (e.g., transparent at top, blurred dark glass when scrolled).
- Include mobile hamburger toggle that smoothly reveals mobile navigation drawer.

4. ANIMATED ACCORDION FAQS:
- FAQs must have smooth toggle animations, rotating chevron icon, and aria-expanded attributes.
- Ensure only one or multiple items can expand cleanly without breaking layout.

5. TOAST NOTIFICATION ENGINE:
- Include a lightweight toast system in the client script:
  * Whenever an action completes (booking submitted, newsletter subscribed, link copied, theme toggled), trigger a sleek floating toast notification at the bottom-right or top-center of the screen.

6. ACCESSIBILITY & MICRO-FEEDBACK:
- Buttons must have :active states (:active:scale-[0.98]).
- Form inputs must have clean focus rings (ring-1 ring-white/40 border-white).
- Proper semantic HTML tags (<header>, <main>, <section>, <article>, <footer>, <nav>).
`;
